version: '3.9'

services:
  nfs-client:
    image: centos:7
    container_name: nsf-client
    stdin_open: true
    tty: true
    volumes:
      - nfs:/test

volumes:
  nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.2.192.8,rw
      device: ":/mnt/tank/csb/www/html"
